import QueryProvider from "@/provider/QueryProvider";
import { LoginBottomSheetProvider } from "@/contexts/LoginBottomSheetContext";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Born-to-run",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <QueryProvider>
        <LoginBottomSheetProvider>
          <body className={`${pretendard.className} bg-[#fcfcfc]`}>
            <div
              id="app-container"
              className="w-full max-w-[786px] mx-auto min-h-screen bg-white"
            >
              {children}
            </div>
          </body>
        </LoginBottomSheetProvider>
      </QueryProvider>
    </html>
  );
}
